name: ci

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

permissions:
  contents: read

jobs:
  dotnet:
    uses: remonenaidoo/swiftbets-platform/.github/workflows/dotnet.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: dotnet
    uses: remonenaidoo/swiftbets-platform/.github/workflows/dotnet-release.yml@main
    permissions:
      contents: write
